### PR TITLE
Make build pipeline parallel

### PR DESCRIPTION
**Pull request by cwansart**
Using the matrix lets the build pipeline in parallel, see my test run: https://github.com/cwansart/microjpa/runs/1995105308

This may speed up the build.

### CODE REVIEW

**Comment by cwansart** [comment]
Or for this run: https://github.com/ArneLimburg/microjpa/runs/1995113470
You can see both parallel runs on the left.

**Comment by ArneLimburg** [comment]
Great addition, but would you please then change the name of the step from "Test with OpenWebBeans" to "Test" or something similar?

**Comment by ArneLimburg** [comment]
Also could you please update deploy.yaml accordingly? I guess we would do the sonar publishing in a separate step then.

**Comment by cwansart** [comment]
Good point. I fixed the step name. I also tried to add the profile matrix to the deploy pipeline. I am not 100 % sure if this works. But if the artifacts remain this should work.

**Pull request merged**
